### ISSUE TITLE
Gemspec Name

### ISSUE THREAD

**Issue by raffibag** [bitmovin/bitcodin-ruby#2]
While preparing to install the client, I noticed a conflict in the instructions:

```
gem build ruby.gemspec
gem install bitcodin-version.gem
```

In order to resolve this, I renamed the gemspec to: `bitcodin.gemspec` and changed the spec_name inside the gemspec manifest to `spec.name  =  "bitcodin"`. 

This yielded the bitcodin-version.gem (specifically, bitcodin-0.1.0.gem), which seems to have installed successfully when I added it to my gemfile.

I'm not sure if this was the correct action to take, but wanted to post the issue so that the instructions can be clarified for future use.

**Comment by moser4035** [comment]
Hi,
Thank you for pointing this out.
I've added these changes and adjusted the README
